Standardised log locations and added set -e to all scripts

diff --git a/roles/common-internal/templates/add_static_routes.sh.j2 b/roles/common-internal/templates/add_static_routes.sh.j2
--- a/roles/common-internal/templates/add_static_routes.sh.j2
+++ b/roles/common-internal/templates/add_static_routes.sh.j2
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# exit on any non-zero
+set -e
+
 echo "Adding static routes on {{ inventory_hostname_short }}"
 
 {% for item in subnets | dict2items %}
